<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors>nullable</WarningsAsErrors>
    <InvariantGlobalization>false</InvariantGlobalization>
    <NeutralLanguage>en</NeutralLanguage>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NuGetAudit>true</NuGetAudit>
    <NuGetAuditMode>direct</NuGetAuditMode>
    <IsPackable>false</IsPackable>
    <Authors>Assem Khaleel Jimzawi</Authors>
    <Company>FoodFlow</Company>
    <Product>FoodFlow</Product>
    <RepositoryUrl>https://github.com/assem-khaleel-jimzawi/foodics-event-driven-platform</RepositoryUrl>
  </PropertyGroup>
</Project>
